# Generated by Django 4.1.13 on 2024-07-16 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_id', models.IntegerField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.FloatField(blank=True, null=True)),
                ('prix_regulier', models.FloatField(blank=True, default=None, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('link', models.URLField()),
                ('page_id', models.IntegerField(blank=True, null=True)),
                ('nombre_visiteur', models.IntegerField(default=0)),
                ('nombre_ajout_favoris', models.IntegerField(default=0)),
                ('nombre_baise_prix', models.IntegerField(default=0)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_products', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_prix', models.FloatField(blank=True, default=None, null=True)),
                ('new_prix', models.FloatField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='scrapping.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='scrapping.product')),
            ],
            options={
                'unique_together': {('user_id', 'product')},
            },
        ),
    ]
